

pipeline:
  restore_cache:
    image: drillster/drone-volume-cache:latest
    restore: true
    mount:
      - /var/lib/docker
    volumes:
      - /tmp/cache:/cache

  ## Build Matlab extension on remote machine
  build_matlab:
    image: amarburg/remote-compile:latest
    hosts: matlab.san.apl.washington.edu
    user: matlab
    target: tempdir
    exclude: .git/
    script:
      - cd Deploy && make build_matlab
    secrets: [ ssh_privkey ]

  ## Build a test docker image
  build_docker:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd Deploy && docker build -t amarburg/covis-postprocess:latest -t amarburg/covis-postprocess:${DRONE_REPO_OWNER}-${DRONE_COMMIT_SHA} .

  ## Test a docker image
  test_docker:
    image: amarburg/covis-postprocess:latest
    commands:
      - ls -al
      - ./mw_python scripts/version.py


  ## Publish resulting image to DockerHub
  publish_docker:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
      - docker push amarburg/covis-postprocess:latest
      - docker push amarburg/covis-postprocess:${DRONE_REPO_OWNER}-${DRONE_COMMIT_SHA}
    secrets:
      - docker_username
      - docker_password


  rebuild_cache:
    image: drillster/drone-volume-cache:latest
    rebuild: true
    mount:
      - /var/lib/docker
    volumes:
      - /tmp/cache:/cache

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
