

pipeline:
  ## Build Matlab python package on remote machine
  build_matlab:
    image: amarburg/remote-compile:latest
    hosts: matlab.san.apl.washington.edu
    user: matlab
    target: tempdir
    script:
      - cd Deploy && make matlab
    secrets: [ ssh_privkey ]

  ## Build a test docker image
  build_docker:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd Deploy && docker build -t amarburg/covis-postprocess:latest -t amarburg/covis-postprocess:${DRONE_REPO_OWNER}-latest -t amarburg/covis-postprocess:${DRONE_REPO_OWNER}-${DRONE_COMMIT_SHA} .

  ## Test a docker image
  pytest_in_docker:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/input:/input:ro
    commands:
      - ls -l /input
      - docker run -i --rm amarburg/covis-postprocess:latest -m pytest

  ## Publish resulting image to DockerHub
  publish_docker:
    image: plugins/docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    repo: amarburg/covis-postprocess
    username: amarburg
    tags:
      - latest
      - ${DRONE_REPO_OWNER}-latest
      - ${DRONE_REPO_OWNER}-${DRONE_COMMIT_SHA}
    secrets:
      - docker_password

  trigger-downstream:
    image: plugins/downstream
    server: https://drone.san.apl.washington.edu:8000
    fork: true
    repositories:
      - ${DRONE_REPO_OWNER}/covis-worker
    secrets: [ downstream_token ]


  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
