version: '3.7'

networks:
  covistest:
    attachable: true

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
  covis_input:
    image: minio/minio
    volumes:
      - ../../:/data
    ports:
      - "9001:9000"
    networks:
      - covistest
    environment:
      MINIO_ACCESS_KEY: covistestdata
      MINIO_SECRET_KEY: covistestdata
    command: server /data
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3

  covis_output:
    image: minio/minio
    volumes:
      - ../output:/data
    ports:
      - "9002:9000"
    networks:
      - covistest
    environment:
      MINIO_ACCESS_KEY: covistestdata
      MINIO_SECRET_KEY: covistestdata
    command: server /data
